// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/p2p/proto/peer.proto

package p2ppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_p2p_proto_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_peer_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_p2p_proto_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_peer_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChainStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainStateRequest) Reset() {
	*x = ChainStateRequest{}
	mi := &file_internal_p2p_proto_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainStateRequest) ProtoMessage() {}

func (x *ChainStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainStateRequest.ProtoReflect.Descriptor instead.
func (*ChainStateRequest) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_peer_proto_rawDescGZIP(), []int{2}
}

func (x *ChainStateRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ChainStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	BestHash      []byte                 `protobuf:"bytes,3,opt,name=best_hash,json=bestHash,proto3" json:"best_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainStateResponse) Reset() {
	*x = ChainStateResponse{}
	mi := &file_internal_p2p_proto_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainStateResponse) ProtoMessage() {}

func (x *ChainStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainStateResponse.ProtoReflect.Descriptor instead.
func (*ChainStateResponse) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_peer_proto_rawDescGZIP(), []int{3}
}

func (x *ChainStateResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ChainStateResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ChainStateResponse) GetBestHash() []byte {
	if x != nil {
		return x.BestHash
	}
	return nil
}

var File_internal_p2p_proto_peer_proto protoreflect.FileDescriptor

const file_internal_p2p_proto_peer_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/p2p/proto/peer.proto\x12\x03p2p\"&\n" +
	"\vPingRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"A\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11ChainStateRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"b\n" +
	"\x12ChainStateResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x1b\n" +
	"\tbest_hash\x18\x03 \x01(\fR\bbestHash2|\n" +
	"\vPeerService\x12+\n" +
	"\x04Ping\x12\x10.p2p.PingRequest\x1a\x11.p2p.PingResponse\x12@\n" +
	"\rGetChainState\x12\x16.p2p.ChainStateRequest\x1a\x17.p2p.ChainStateResponseB=Z;github.com/CrawlerLi/myMiniBitcoin/internal/p2p/proto;p2ppbb\x06proto3"

var (
	file_internal_p2p_proto_peer_proto_rawDescOnce sync.Once
	file_internal_p2p_proto_peer_proto_rawDescData []byte
)

func file_internal_p2p_proto_peer_proto_rawDescGZIP() []byte {
	file_internal_p2p_proto_peer_proto_rawDescOnce.Do(func() {
		file_internal_p2p_proto_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_p2p_proto_peer_proto_rawDesc), len(file_internal_p2p_proto_peer_proto_rawDesc)))
	})
	return file_internal_p2p_proto_peer_proto_rawDescData
}

var file_internal_p2p_proto_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_p2p_proto_peer_proto_goTypes = []any{
	(*PingRequest)(nil),        // 0: p2p.PingRequest
	(*PingResponse)(nil),       // 1: p2p.PingResponse
	(*ChainStateRequest)(nil),  // 2: p2p.ChainStateRequest
	(*ChainStateResponse)(nil), // 3: p2p.ChainStateResponse
}
var file_internal_p2p_proto_peer_proto_depIdxs = []int32{
	0, // 0: p2p.PeerService.Ping:input_type -> p2p.PingRequest
	2, // 1: p2p.PeerService.GetChainState:input_type -> p2p.ChainStateRequest
	1, // 2: p2p.PeerService.Ping:output_type -> p2p.PingResponse
	3, // 3: p2p.PeerService.GetChainState:output_type -> p2p.ChainStateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_p2p_proto_peer_proto_init() }
func file_internal_p2p_proto_peer_proto_init() {
	if File_internal_p2p_proto_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_p2p_proto_peer_proto_rawDesc), len(file_internal_p2p_proto_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_p2p_proto_peer_proto_goTypes,
		DependencyIndexes: file_internal_p2p_proto_peer_proto_depIdxs,
		MessageInfos:      file_internal_p2p_proto_peer_proto_msgTypes,
	}.Build()
	File_internal_p2p_proto_peer_proto = out.File
	file_internal_p2p_proto_peer_proto_goTypes = nil
	file_internal_p2p_proto_peer_proto_depIdxs = nil
}
